// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ__B9AA5Wl5NjIYR0K_tEdfN40xEqgvU',
    appId: '1:644497889566:web:9a851187fb82169462510f',
    messagingSenderId: '644497889566',
    projectId: 'cryptowise-72c0a',
    authDomain: 'cryptowise-72c0a.firebaseapp.com',
    databaseURL: 'https://cryptowise-72c0a-default-rtdb.firebaseio.com',
    storageBucket: 'cryptowise-72c0a.firebasestorage.app',
    measurementId: 'G-Y0P3XX7CQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrQI-ifVW0NKbqtdjWgLHZ5QtsSZ_MKjA',
    appId: '1:644497889566:android:a90e590c58e6f23e62510f',
    messagingSenderId: '644497889566',
    projectId: 'cryptowise-72c0a',
    databaseURL: 'https://cryptowise-72c0a-default-rtdb.firebaseio.com',
    storageBucket: 'cryptowise-72c0a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4CS7SywLb44QFXThCmWKafucR9lofeqk',
    appId: '1:644497889566:ios:10f31a6fb9c19aa062510f',
    messagingSenderId: '644497889566',
    projectId: 'cryptowise-72c0a',
    databaseURL: 'https://cryptowise-72c0a-default-rtdb.firebaseio.com',
    storageBucket: 'cryptowise-72c0a.firebasestorage.app',
    iosBundleId: 'com.example.cryptowise',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4CS7SywLb44QFXThCmWKafucR9lofeqk',
    appId: '1:644497889566:ios:10f31a6fb9c19aa062510f',
    messagingSenderId: '644497889566',
    projectId: 'cryptowise-72c0a',
    databaseURL: 'https://cryptowise-72c0a-default-rtdb.firebaseio.com',
    storageBucket: 'cryptowise-72c0a.firebasestorage.app',
    iosBundleId: 'com.example.cryptowise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ__B9AA5Wl5NjIYR0K_tEdfN40xEqgvU',
    appId: '1:644497889566:web:71b60040a9a5c25162510f',
    messagingSenderId: '644497889566',
    projectId: 'cryptowise-72c0a',
    authDomain: 'cryptowise-72c0a.firebaseapp.com',
    databaseURL: 'https://cryptowise-72c0a-default-rtdb.firebaseio.com',
    storageBucket: 'cryptowise-72c0a.firebasestorage.app',
    measurementId: 'G-9NKE77GDEC',
  );
}
